---
dependencies:
  # Ensure the configuration is loaded and the proper variables are set.
  - role: config.detection
    required_vars:
      - webserver
      - webserver_owner
      - ntp_timezone
      - certbot_dir

  # Install the nginx server with configuration defaults.
  - role: geerlingguy.nginx
    vars:
      nginx_upstreams:
        - name: '_php_apps'
          servers:
            - '127.0.0.1:9000 max_fails=0'

      nginx_extra_http_options: |
            map $http_connect_state $acessl {
                SSL on;
            }
    become: true
    become_user: root
    when: webserver == 'nginx'

  # Install the php-fpm support for nginx.
  - role: geerlingguy.php
    vars:
      php_packages:
        - php
        - php-cli
        - php-fpm
        - php-opcache
        - php-pecl-apcu
        - php-mbstring
        - php-mcrypt
        - php-gd
        - php-pdo
        - php-pdo_mysql
        - php-soap
        - php-xml
    php_enablerepo: remi-php70
    php_date_timezone: "{{ ntp_timezone }}"
    php_enable_webserver: true
    php_enable_php_fpm: true
    php_webserver_daemon: 'nginx'
    php_fpm_pool_user: 'nginx'
    php_fpm_pool_group: 'nginx'
    become: true
    become_user: root
    when: webserver == 'nginx'

  # Install the certbot as this will be used regardless of the webserver.
  - role: geerlingguy.certbot
    vars:
      certbot_auto_renew_user: "{{ webserver_owner }}"
    become: true
    become_user: root
    when: not certbot_ignore

