---
dependencies:
  # Ensure the configuration is loaded and the proper variables are set.
  - role: config.detection
    required_vars:
      - dbserver
      - dbserver_dir
      - dbserver_user
      - dbserver_group

  # Ensure data directory has the correct permissions for selinux.
  - role: environ.selinux
    vars:
      selinux_path: "{{ dbserver_dir }}"
      selinux_context: mysqld_db_t
      path: "{{ dbserver_dir }}"
      path_user: "{{ dbserver_user }}"
      path_group: "{{ dbserver_group }}"
      path_state: directory
    become: true
    become_user: root

  # Install the mariadb database server
  - role: geerlingguy.mysql
    vars:
      mysql_packages:
        - mariadb
        - mariadb-server
      mysql_datadir: "{{ dbserver_dir }}"
    become: true
    become_user: root
    when: dbserver == 'mariadb' and ansible_os_family == "RedHat"

